max_symbols: 2
random_caps_per_variant: 2
min_password_length: 8
max_password_length: 24
use_years: false
use_keyboard_walks: false
use_leetspeak: false
symbols: ['!', '@', '#', '$', '%', '&', '*', '?', '1', '2', '3', '.', '_', '-']
real_world_leet:
  a: ['@', '4']
  e: ['3']
  i: ['1', '!']
  o: ['0']
  s: ['$', '5']
  t: ['7']
  l: ['1']
  b: ['8'] 
  g: ['9']
  z: ['2']
keyboard_walks:
  - qwerty
  - asdfgh
  - zxcvbn
  - 123456
  - 654321
  - qazwsx
  - 1qaz2wsx
  - qweasd
  - poiuy
  - mnbvcx
years: 
  - "2025"
  - "2024"
  - "2023"
  - "2022"
  - "2021"
  - "2020"
  - "2019"
  - "2018"
  - "2017"
  - "2016"
  - "2015"
  - "2014"
  - "2013"
  - "2012"
  - "2011"
  - "2010"
  - "09"
  - "08"
  - "07"
  - "06"
  - "05"
  - "04"
  - "03"
  - "02"
  - "01"
  - "00"
